language: python

python:
    - "2.7"
    - "3.4"

env:
    - DJANGO_VERSION=1.5.10 SAMPLE_PROJECT=sample_project
    - DJANGO_VERSION=1.6.7 SAMPLE_PROJECT=sample_project
    - DJANGO_VERSION=1.7 SAMPLE_PROJECT=sample_project

branches:
    only:
        - master

matrix:
    exclude:
        -
            python: "2.7"
            env: DJANGO_VERSION=1.5.10 SAMPLE_PROJECT=sample_project

        -
            python: "2.7"
            env: DJANGO_VERSION=1.7 SAMPLE_PROJECT=python3_sample_project

        -
            python: "3.4"
            env: DJANGO_VERSION=1.5.10 SAMPLE_PROJECT=sample_project

        -
            python: "3.4"
            env: DJANGO_VERSION=1.6.7 SAMPLE_PROJECT=sample_project

        -
            python: "3.4"
            env: DJANGO_VERSION=1.7 SAMPLE_PROJECT=sample_project

install:
    - pip install django==$DJANGO_VERSION

script:
    - cd $SAMPLE_PROJECT
    - python manage.py test
